# Generated by Django 3.2.16 on 2022-10-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goals1', models.IntegerField(default=0)),
                ('goals2', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1_id', to='lab1_App.teams')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2_id', to='lab1_App.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab1_App.users')),
            ],
        ),
    ]
