# Generated by Django 3.2.16 on 2022-10-29 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='goals1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='goals2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='lab1_App.teams'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='lab1_App.teams'),
        ),
    ]
