# Generated by Django 3.2.16 on 2022-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_App', '0002_auto_20221029_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='nickname',
            field=models.CharField(default='A', max_length=1000),
            preserve_default=False,
        ),
    ]
