# Generated by Django 3.2.9 on 2022-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_App', '0006_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='abc123', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='abc123', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='abc123', max_length=1000),
            preserve_default=False,
        ),
    ]
