# Generated by Django 3.2.16 on 2022-10-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_App', '0003_teams_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='team1_id',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='team2_id',
            new_name='team2',
        ),
    ]
